param(
    [string]$BaseImageReport = "artifacts/base-image-matrix-report.json",
    [string]$OOBEReport = "artifacts/wsl-images-oobe-matrix-report.json",
    [string]$ReadmePath = "README.md"
)

$ErrorActionPreference = "Stop"

function Resolve-PathSafe([string]$PathValue) {
    if ([System.IO.Path]::IsPathRooted($PathValue)) {
        return $PathValue
    }
    return Join-Path (Get-Location) $PathValue
}

function Read-JsonReport([string]$PathValue) {
    if (-not (Test-Path $PathValue)) {
        return $null
    }
    $raw = Get-Content -Path $PathValue -Raw -Encoding UTF8
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return $null
    }
    return $raw | ConvertFrom-Json
}

function Status-Label([string]$Status) {
    switch ($Status) {
        "pass" { return "PASS" }
        "fail" { return "FAIL" }
        "skip" { return "SKIP" }
        default { return "UNKNOWN" }
    }
}

function Escape-Pipe([string]$Value) {
    if ($null -eq $Value) { return "" }
    return ($Value -replace "\|", "\\|")
}

function Render-MatrixBlock([string]$Title, $Report) {
    $lines = @()
    $lines += "### $Title"
    $reportProps = @()
    if ($null -ne $Report -and $null -ne $Report.PSObject) {
        $reportProps = @($Report.PSObject.Properties.Name)
    }
    if ($null -eq $Report -or $Report -is [string] -or -not ($reportProps -contains "results")) {
        $lines += ""
        $lines += "_No report available yet._"
        $lines += ""
        return $lines
    }

    $generatedAt = ""
    if ($Report.generatedAt) {
        try {
            $generatedAt = [DateTime]::Parse($Report.generatedAt).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'")
        } catch {
            $generatedAt = [string]$Report.generatedAt
        }
    }

    $okText = if ($Report.ok) { "PASS" } else { "FAIL" }
    $lines += ""
    $lines += "- Last run: $generatedAt"
    $lines += "- Summary: **$okText** ($($Report.passed) passed, $($Report.failed) failed, $($Report.skipped) skipped, total $($Report.total))"
    $lines += ""
    $lines += "| Image | Status | Elapsed (s) |"
    $lines += "| --- | --- | ---: |"
    foreach ($entry in @($Report.results)) {
        $image = Escape-Pipe([string]$entry.image)
        $status = Status-Label([string]$entry.status)
        $elapsed = ""
        if ($null -ne $entry.elapsed) {
            try { $elapsed = [string]([Math]::Round([double]$entry.elapsed, 2)) } catch { $elapsed = [string]$entry.elapsed }
        }
        $lines += "| ``$image`` | $status | $elapsed |"
    }
    $lines += ""
    return $lines
}

$resolvedBase = Resolve-PathSafe $BaseImageReport
$resolvedOOBE = Resolve-PathSafe $OOBEReport
$resolvedReadme = Resolve-PathSafe $ReadmePath

$baseMatrixReportData = Read-JsonReport $resolvedBase
$oobeMatrixReportData = Read-JsonReport $resolvedOOBE

if (-not (Test-Path $resolvedReadme)) {
    throw "README not found: $resolvedReadme"
}

$readme = Get-Content -Path $resolvedReadme -Raw -Encoding UTF8

$startMarker = "<!-- WSLB:COMPATIBILITY:START -->"
$endMarker = "<!-- WSLB:COMPATIBILITY:END -->"

$blockLines = @()
$blockLines += $startMarker
$blockLines += "## Compatibility Matrix"
$blockLines += ""
$blockLines += "_This section is auto-generated by GitHub Actions (`Compatibility Matrix` workflow)._"
$blockLines += ""
$blockLines += (Render-MatrixBlock "Base Image Matrix" $baseMatrixReportData)
$blockLines += (Render-MatrixBlock "Official WSL Images OOBE Matrix" $oobeMatrixReportData)
$blockLines += $endMarker
$newBlock = ($blockLines -join "`n")

if ($readme.Contains($startMarker) -and $readme.Contains($endMarker)) {
    $pattern = [regex]::Escape($startMarker) + "[\s\S]*?" + [regex]::Escape($endMarker)
    $updated = [regex]::Replace($readme, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $newBlock })
} else {
    $updated = $readme.TrimEnd() + "`n`n" + $newBlock + "`n"
}

if ($updated -ne $readme) {
    Set-Content -Path $resolvedReadme -Value $updated -Encoding UTF8
    Write-Host "README updated: $resolvedReadme"
} else {
    Write-Host "README compatibility block unchanged."
}
