name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (x.y.z)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release-branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Set Version Variable
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"

      - name: Create Release Branch
        run: |
          git checkout -b "release/${VERSION}"

      - name: Update version.go
        run: |
          if [ -f "internal/version/version.go" ]; then
            if grep -q "Version = \"${VERSION}\"" internal/version/version.go; then
              echo "internal/version/version.go already contains ${VERSION}"
            else
              sed -i "s/Version = \".*\"/Version = \"${VERSION}\"/" internal/version/version.go
              git add internal/version/version.go
              git commit -m "chore: update version.go to ${VERSION}"
            fi
          else
            echo "Version file not found at internal/version/version.go"
            exit 1
          fi

      - name: Push Release Branch
        run: |
          git push -u origin "release/${VERSION}"
          echo "::notice::Successfully created release/${VERSION} branch"