name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (without v prefix)'
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update version.go file
        run: |
          sed -i "s/Version = \".*\"/Version = \"${{ github.event.inputs.version }}\"/" internal/version/version.go
          cat internal/version/version.go

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add internal/version/version.go
          git commit -m "Prepare release v${{ github.event.inputs.version }}"

      - name: Push changes
        run: git push origin main

      - name: Create tag
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release v${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}