name: Release Go Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Update version.go file with the correct version from tag
      - name: Update version.go file
        run: |
          sed -i "s/Version = \".*\"/Version = \"${{ env.VERSION }}\"/" internal/version/version.go
          cat internal/version/version.go

      - name: Build for Windows and Linux
        run: |
          VERSION=${{ env.VERSION }}
          # Build Windows binary
          GOOS=windows GOARCH=amd64 go build -o ./bin/wslb.exe .
          # Build Linux binary
          GOOS=linux GOARCH=amd64 go build -o ./bin/wslb .

      - name: Calculate SHA256 hash
        run: |
          HASH=$(sha256sum ./bin/wslb.exe | awk '{print $1}')
          echo "HASH=$HASH" >> $GITHUB_ENV

      - name: Create updated version-specific package file
        run: |
          # Create version-specific package file for this release
          cat <<EOF > ./bin/wslb-package-v${{ env.VERSION }}.json
          {
            "name": "wslb",
            "version": "${{ env.VERSION }}",
            "description": "WSLB – A tool for managing WSL binaries",
            "homepage": "https://github.com/wsl-images/wslb",
            "license": "MIT",
            "url": "https://github.com/wsl-images/wslb/releases/download/v${{ env.VERSION }}/wslb.exe",
            "hash": "sha256:${{ env.HASH }}",
            "architecture": {
              "64bit": {
                "bin": ["wslb.exe"]
              }
            },
            "autoupdate": {
              "url": "https://github.com/wsl-images/wslb/releases/download/v\$version/wslb.exe"
            },
            "checkver": {
              "github": "https://github.com/wsl-images/wslb"
            }
          }
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: WSLB v${{ env.VERSION }}
          files: |
            ./bin/wslb.exe
            ./bin/wslb
            ./bin/wslb-package-v${{ env.VERSION }}.json
          generate_release_notes: true
          body: |
            ## WSLB v${{ env.VERSION }}

            ### Installation

            Install with Go:
            ```
            go install github.com/wsl-images/wslb@v${{ env.VERSION }}
            ```

            Install with Scoop (version-specific):
            ```
            scoop install https://github.com/wsl-images/wslb/releases/download/v${{ env.VERSION }}/wslb-package-v${{ env.VERSION }}.json
            ```

            Or install latest version:
            ```
            scoop install https://raw.githubusercontent.com/wsl-images/wslb/main/wslb-package.json
            ```

            Or download the binary directly from the assets below.

      # Update the main branch package as well
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update version.go file on main
        run: |
          sed -i "s/Version = \".*\"/Version = \"${{ env.VERSION }}\"/" internal/version/version.go

      - name: Update wslb-package.json on main
        run: |
          cat <<EOF > wslb-package.json
          {
            "name": "wslb",
            "version": "${{ env.VERSION }}",
            "description": "WSLB – A tool for managing WSL binaries",
            "homepage": "https://github.com/wsl-images/wslb",
            "license": "MIT",
            "url": "https://github.com/wsl-images/wslb/releases/download/v${{ env.VERSION }}/wslb.exe",
            "hash": "sha256:${{ env.HASH }}",
            "architecture": {
              "64bit": {
                "bin": ["wslb.exe"]
              }
            },
            "autoupdate": {
              "url": "https://github.com/wsl-images/wslb/releases/download/v\$version/wslb.exe"
            },
            "checkver": {
              "github": "https://github.com/wsl-images/wslb"
            }
          }
          EOF

      - name: Commit and push updated files to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add wslb-package.json internal/version/version.go
          git commit -m "Update version to v${{ env.VERSION }}"
          git push origin main